# Generated by Django 3.1.4 on 2020-12-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_create', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('image', models.ImageField(max_length=1000, upload_to='', verbose_name=models.CharField(max_length=50))),
            ],
        ),
        migrations.CreateModel(
            name='Mui_huong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=40)),
                ('image', models.ManyToManyField(related_name='image_mui_huong', to='perfume.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Pha_che',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=40)),
                ('gioi_thieu', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Thuong_hieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
                ('gioi_thieu', models.TextField()),
                ('website', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Nuoc_hoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=40)),
                ('nhom_nuoc_hoa', models.CharField(blank=True, max_length=60, null=True)),
                ('gioi_tinh', models.CharField(blank=True, max_length=8, null=True)),
                ('do_tuoi', models.CharField(blank=True, max_length=70, null=True)),
                ('nam_sx', models.CharField(blank=True, max_length=70, null=True)),
                ('nong_do', models.CharField(blank=True, max_length=30, null=True)),
                ('do_luu', models.CharField(blank=True, max_length=30, null=True)),
                ('do_toa', models.CharField(blank=True, max_length=30, null=True)),
                ('khuyen_dung', models.CharField(blank=True, max_length=60, null=True)),
                ('phong_cach', models.CharField(blank=True, max_length=80, null=True)),
                ('diem', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tong_quan', models.TextField()),
                ('chi_tiet', models.TextField()),
                ('huong_chinh', models.ManyToManyField(related_name='huong_chinh', to='perfume.Mui_huong')),
                ('huong_cuoi', models.ManyToManyField(related_name='huong_cuoi', to='perfume.Mui_huong')),
                ('huong_dau', models.ManyToManyField(related_name='huong_dau', to='perfume.Mui_huong')),
                ('image', models.ManyToManyField(related_name='image_nuuoc_hoa', to='perfume.Image')),
                ('pha_che', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pha_che', to='perfume.pha_che')),
                ('thuong_hieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thuong_hieu', to='perfume.thuong_hieu')),
            ],
        ),
        migrations.CreateModel(
            name='Nhom_huong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=40)),
                ('mo_ta', models.TextField()),
                ('image', models.ManyToManyField(related_name='image_nhom_huong', to='perfume.Image')),
            ],
        ),
        migrations.AddField(
            model_name='mui_huong',
            name='nhom_mui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhom_huong', to='perfume.nhom_huong'),
        ),
        migrations.CreateModel(
            name='Gia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.IntegerField()),
                ('dia_diem', models.CharField(max_length=50)),
                ('nuoc_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuoc_hoa', to='perfume.nuoc_hoa')),
            ],
        ),
    ]
