# Generated by Django 3.1.4 on 2020-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ManyToManyField(related_name='image_blog', to='perfume.Image'),
        ),
    ]
