# Generated by Django 3.1.4 on 2020-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mui_huong',
            name='mo_ta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nhom_huong',
            name='mo_ta',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='pha_che',
            name='image',
        ),
        migrations.AddField(
            model_name='pha_che',
            name='image',
            field=models.ManyToManyField(related_name='image_pha_che', to='perfume.Image'),
        ),
        migrations.RemoveField(
            model_name='thuong_hieu',
            name='image',
        ),
        migrations.AddField(
            model_name='thuong_hieu',
            name='image',
            field=models.ManyToManyField(related_name='image_thuong_heu', to='perfume.Image'),
        ),
    ]
