# Generated by Django 3.1.4 on 2020-12-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0003_auto_20201221_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='nuoc_hoa',
            name='huong_chinh',
            field=models.ManyToManyField(blank=True, null=True, related_name='huong_chinh', to='perfume.Mui_huong'),
        ),
        migrations.AlterField(
            model_name='nuoc_hoa',
            name='huong_cuoi',
            field=models.ManyToManyField(blank=True, null=True, related_name='huong_cuoi', to='perfume.Mui_huong'),
        ),
        migrations.AlterField(
            model_name='nuoc_hoa',
            name='huong_dau',
            field=models.ManyToManyField(blank=True, null=True, related_name='huong_dau', to='perfume.Mui_huong'),
        ),
    ]
